# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='incident_location_type',
            field=models.CharField(choices=[('home', 'Home'), ('public_space', 'Public Space'), ('work_site', 'Work Site'), ('government_office', 'Government office')], max_length=50),
        ),
    ]
