# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180627_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='complainant_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='complainant_telephone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='incident_location_city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
